= mathml2asciimath

image:https://img.shields.io/gem/v/mathml2asciimath.svg["Gem Version", link="https://rubygems.org/gems/mathml2asciimath"]
image:https://img.shields.io/travis/riboseinc/mathml2asciimath/master.svg["Build Status", link="https://travis-ci.org/riboseinc/mathml2asciimath"]
image:https://codeclimate.com/github/riboseinc/mathml2asciimath/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/mathml2asciimath"]

Ruby gem to convert MathML into AsciiMath

Ignores style and MathML attributes (other than `mfenced/@open`, `mfenced/@close`, `mo/@fence`).

Processes the following MathML tags: `mrow, mfenced, msqrt, mfrac, msup, msub, munderover, msubsup, munder, mover, mi, mn, ntext, mo, mtable, mtr, mtd`.

Converts all the Unicode characters MathJax knows about into AsciiMath operators (e.g. `\\beta, xx, oint`)

As with the other two MathML to AsciiMath converters available online (Python: https://github.com/rochecompaan/upfront.mathml2asciimath, Node.js: https://github.com/learningobjectsinc/mathml-to-asciimath), this converter is not foolproof, production-ready, or complete, and you will need to post-edit output. It's still a lot better than nothing. (And because it converts Unicode to Ascii, it's a lot better than the other two.)

